run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocyclo
    - gofmt
    - goimports
    - revive
    - misspell
    - dogsled
    - nakedret
    - gocritic
    - godot
    - nestif

linters-settings:
  gocyclo:
    min-complexity: 15
  nestif:
    min-complexity: 5
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
  gocritic:
    enabled-checks:
      - boolExprSimplify
      - builtinShadow
      - rangeValCopy
      - appendCombine
      - commentedOutCode
      - yodaStyleExpr

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0