name: Generate Missing Descriptions
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  generate-descriptions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0  # Required for proper git diff

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      id: deps
      run: |
        cd .github/scripts
        rm -rf node_modules package-lock.json  # Clear old installations
        npm install

    - name: Generate missing descriptions
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        cd .github/scripts
        npm start

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success()
      run: |
        # Configure git authentication
        git remote set-url --push origin https://joseph-uk:$GITHUB_TOKEN@github.com/your/repo
        
        # Configure git
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        
        # Check for actual changes
        echo "Changed files:"
        git status --porcelain

        # Add all potential changes
        git add data/apps/
        git add .github/scripts/package-lock.json  # If needed
        
        # Commit only if changes exist
        if [[ -n $(git status --porcelain) ]]; then
          echo "🚀 Committing changes..."
          git commit -m "Auto-generated missing descriptions"
          git pull --rebase
          git push
        else
          echo "❌ No changes detected - nothing to commit"
        fi