name: Update CSV Data

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Download CSV
      run: |
        mkdir -p data
        curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTTebtcc367STxJXR6VWwH_wDke9hrwHgwJYdUCkdKK6VgrO_L6f04OqtgruNvzEIlQ_k8bS8AxNpmg/pub?output=csv" \
          --fail --output public/data/paragliding-apps.csv

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/paragliding-apps.csv
        git diff-index --quiet HEAD || git commit -m "Update CSV data [automated]"
        git push
