name: Update Google Sheets Data

on:
  workflow_dispatch:    
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and process Google Sheet data
      env:
        SHEET_ID: 2PACX-1vTTebtcc367STxJXR6VWwH_wDke9hrwHgwJYdUCkdKK6VgrO_L6f04OqtgruNvzEIlQ_k8bS8AxNpmg
        API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
      run: |
        python - << EOF
        import os
        import requests
        import json
        import csv
        from io import StringIO

        sheet_id = os.environ['SHEET_ID']
        api_key = os.environ['API_KEY']
        output_file = 'data/sheet-data.json'  # Change this to your desired path

        # Fetch data from Google Sheets API
        url = f'https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values/Items?key={api_key}'
        response = requests.get(url)
        response.raise_for_status()
        
        # Convert to JSON
        values = response.json().get('values', [])
        
        # Convert rows to dictionary
        headers = values[0]
        data = []
        for row in values[1:]:
            data.append(dict(zip(headers, row)))
        
        # Save as JSON
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"Successfully saved {len(data)} records to {output_file}")
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update sheet data"
        git push
